name: Build and Test

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  generate:
    name: code generation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler
      - name: install python tools
        run: pip install -r requirements.txt
      - name: generate code
        run: ./generate_from_protos.bash

  cpp:
    name: cpp
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: sudo apt-get update && sudo apt-get install -y libgtest-dev
      - name: configure
        run: cmake -DCMAKE_INSTALL_PREFIX=cpp/build/install -Bcpp/build -Scpp
      - name: build
        run: cmake --build cpp/build --target install
      - name: test
        run: ./cpp/build/test/tests

  py:
    name: py
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: configure dependencies
        run: cmake -DCMAKE_INSTALL_PREFIX=py/dependencies/build/install -Bpy/dependencies/build -Spy/dependencies
      - name: build and install dependencies
        run: cmake --build py/dependencies/build
      - name: configure
        run: cmake -DCMAKE_PREFIX_PATH=$(pwd)/py/dependencies/build/install -Bpy/build -Spy
      - name: build
        run: cmake --build py/build

  swift:
    name: swift
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: configure dependencies
        run: cmake -DCMAKE_INSTALL_PREFIX=swift/build/macos/install -Bswift/build/macos -Sswift/dependencies
      - name: build and install dependencies
        run: cmake --build swift/build/macos
      - name: Assemble xcframework
        run: BUILD_DIR=$(pwd)/swift/build bash $(pwd)/cpp/tools/assemble_xcframework.sh
      - name: Build Swift library
        run: swift build --package-path swift/ExampleLibrary
      - name: Run Swift tests
        run: swift test --package-path swift/ExampleLibrary

